import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  txtQualityDownShare: {
    position: 'absolute',
    bottom: -13,
    fontSize: 11,
    color: 'rgba(51,51,51,0.5)',
  },
  slider: {
    height: 30,
    width: 200,
  },
  txtInfoSlider: {
    fontSize: 11,
    color: 'rgba(51,51,51,0.5)',
  },
  vwSlider: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnClose: {
    height: 30,
    width: 30,
    backgroundColor: 'rgba(51,51,51,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    position: 'absolute',
    right: 15,
    top: 15,
  },
  ModalBody: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'center',
    borderTopRightRadius: 35,
    borderTopLeftRadius: 35,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: 'rgba(51,51,51,0.1)',
    elevation: 3,
  },
  VwConfirmFabric: {
    backgroundColor: '#c22f47',
    width: 120,
    height: 40,
    borderRadius: 50,
    marginBottom: 15,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtConfirm: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  txtFabric: {
    fontSize: 10,
    color: '#c22f47',
    marginBottom: 15,
    textAlign: 'center',
    fontWeight: 'bold',
    maxWidth: '65%',
  },
  vwBody: {
    marginTop: 5,
    marginBottom: 5,
    width: '100%',
    alignItems: 'center',
  },
  modal: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(51,51,51,0.2)',
  },
  lastBox: {
    width: '100%',
    alignItems: 'center',
  },
  vwLabelCor: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
  },
  txtCorFundo: {
    fontSize: 25,
    padding: 10,
    color: '#212121',
    fontWeight: 'bold',
  },
  touchOK: {
    width: 140,
    height: 50,
    borderRadius: 30,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#90ee90',
    elevation: 3,
  },
  txtOK: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#006400',
  },
  themeSelector: {
    width: '70%',
  },
  keyboardSelector: {
    width: '30%',
    marginTop: 5,
  },
  txtInfoKey: {
    fontSize: 11,
    color: 'rgba(51,51,51,0.5)',
    maxWidth: '70%',
    textAlign: 'center',
  },
});
